apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-react
  template:
    metadata:
      labels:
        app: hello-world-react
    spec:
      containers:
      - name: hello-world-react
        image: public.ecr.aws/533267116885/matban/hello-world-react:latest
        ports:
        - containerPort: 80