apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-react-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - cirrina.matban.uk
    secretName: yourdomain-tls
  rules:
  - host: cirrina.matban.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-react-service
            port:
              number: 80